version: '3'
services:
  nginx:
    image: nginx:alpine
    container_name: nginx_server
    ports:
      - 8080:80
      - 8443:443
    volumes:
      - ./src:/src
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
  php:
    image: php:7.4-fpm-alpine
    container_name: php_web
    volumes:
      - ./src:/src