version: '3'
services:
  nginx:
    image: nginx:alpine
    container_name: nginx_server
    ports:
      - 8080:80
      - 8443:443
    volumes:
      - ./src:/usr/app/src
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
  php:
    container_name: php_web
    build:
      context: .
    image: php-nginx/dev