version: '3'
services:
  nginx:
    image: nginx:alpine
    container_name: nginx_server
    ports:
      - 8080:80
      - 8443:443
    volumes:
      - ./src:/usr/app/src
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
  php:
    container_name: php_web
    build:
      context: .
      target: prod
    image: php-nginx/dev
    command: sh -c "curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin --filename=composer"
    command: composer install
    command: php-fpm -F
    volumes:
      - ./src:/usr/app/src
      - ./composer.json:/usr/app/composer.json
      - ./composer.lock:/usr/app/composer.lock